
title: My Resume
url: 'www.lalet.me'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Lalet Scaria
tagline: Master's Student
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: laletscaria+site@gmail.com
phone: 514-295-24(eight)(eight)
website: 'www.lalet.me'  #do not add http://
linkedin: laletscaria
github: lalet
twitter: '@laletscaria'


# Tracker
analytics: #UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
